# Project: TerraSpotter Platform
# Author: Om Borekar
# Year: 2026
# Description: Application configuration properties for the TerraSpotter backend.

spring.application.name=TerraSpoter

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Local run examples removed for security

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


server.port=${PORT:8080}
spring.mvc.contentnegotiation.favor-path-extension=true
# Session
server.servlet.session.timeout=30m
server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.path=/

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB
spring.web.resources.static-locations=classpath:/static/,file:uploads/
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=true

# CORS URL
frontend.url=${FRONTEND_URL:http://localhost:5173}

#Deploy Use
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

brevo.api-key=${BREVO_API_KEY}
brevo.sender-email=${BREVO_SENDER_EMAIL}
brevo.sender-name=${BREVO_SENDER_NAME}

# Gemini AI
gemini.api.key=${GEMINI_API_KEY:}
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent}
